### ISSUE TITLE
version numberof pbiviz.json  must have 4 parts 

### ISSUE THREAD

**Issue by xiaodongliang** [autodesk-platform-services/aps-powerbi-tools#7]
With installing latest version of pbiviz (5.4.1), npm start will throw the errors below.

The version number in pbiviz.json must have 4 parts. e.g.

`version: 0.0.6.0`

after changing with 4 parts, it can work now.

![pbiissue](https://github.com/autodesk-platform-services/aps-powerbi-tools/assets/5087461/0ab6ff09-0aa5-4ff2-aaad-491fb3f4123f)

**Comment by petrbroz** [comment]
Thank you for the heads up @xiaodongliang :+1: There were couple more issues with the new version of `pbiviz`, for example, `pbiviz package` command stopped working as well. I updated all the dependencies in the project based on what `pbiviz new ...` does, and that helped.
